GET http://127.0.0.1:4000/favourites
###

GET http://127.0.0.1:3000/About?location=Leeds,%20GB

###

GET http://127.0.0.1:3000/About?location=scarb

###

POST http://127.0.0.1:3000/newuser
content-type: application/json
{
    "username": "testGeezer",
    "password": "test",
    "email": "test.geezer@test.com",
    "name": "Test Geezer"            
}

POST http://127.0.0.1:3000/login
content-type: application/json
{
    "username": "testGeezer",
    "password": "test",
    
}